<?php

return [
    'support' => [
        'email' => 'admin@joudahstore.com',
        'phone' => '6281234567890',
        'whatsapp' => '6281234567890',
    ],

    'locations' => [
        [
            'name' => 'TOKO ABU ALI',
            'city' => 'Jakarta Timur',
            'province' => 'DKI Jakarta',
            'phone' => '6285781110280',
            'address' => 'Jl. Raya Condet No.25D, RT.7/RW.7, Cililitan, Kec. Kramat jati, Kota Jakarta Timur, DKI Jakarta 13640',
            'lat' => -6.2626,
            'lng' => 106.8669,
            'featured' => true,
        ],
        [
            'name' => 'TOKO MEKAH MADINAH',
            'city' => 'Jakarta Pusat',
            'province' => 'DKI Jakarta',
            'phone' => '6287770609387',
            'address' => 'Pusat Grosir Tanah Abang Blok A. Lt. SLG Los. F No. 70, Jl. K.H. Mas Mansyur, RT.5/RW.13, Kp. Bali, Kecamatan Tanah Abang, Kota Jakarta Pusat, DKI Jakarta 10250',
            'lat' => -6.1885,
            'lng' => 106.8147,
            'featured' => true,
        ],
        [
            'name' => 'AL-MANSHUROH AGENCY',
            'city' => 'Semarang',
            'province' => 'Jawa Tengah',
            'phone' => '6285326313006',
            'address' => 'Jalan Prof. Soedarto, Ruko A No 1, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50725',
            'lat' => -6.9903,
            'lng' => 110.4201,
            'featured' => true,
        ],
        [
            'name' => 'LATANSA PARFUM',
            'city' => 'Pontianak',
            'province' => 'Kalimantan Barat',
            'phone' => '6282254145000',
            'address' => 'Jl. H. Rais A. Rachman Sungai Jawi, Samping Bukit Barisan Kec. Pontianak Kota Pontianak - Kalimantan Barat',
            'lat' => -0.0263,
            'lng' => 109.3425,
            'featured' => false,
        ],
        [
            'name' => 'GERAI BARAKA',
            'city' => 'Depok',
            'province' => 'Jawa Barat',
            'phone' => '6287788339956',
            'address' => 'D\'Arjuna Blok C4, RT.03 RW.12, Kel. Ratu Jaya, Kec. Cipayung, Kota Depok, Jawa Barat 16439',
            'lat' => -6.3977,
            'lng' => 106.8206,
            'featured' => false,
        ],
        [
            'name' => 'SAUDI STORE',
            'city' => 'Banda Aceh',
            'province' => 'Aceh',
            'phone' => '6285260009005',
            'address' => 'Jl. Dr. Mr. Mohd Hasan No.73, Sukadamai, Kec. Lueng Bata, Kota Banda Aceh, Aceh 23127',
            'lat' => 5.5471,
            'lng' => 95.3207,
            'featured' => false,
        ],
        [
            'name' => 'TOKO INAL SIREGAR',
            'city' => 'Padang Sidempuan',
            'province' => 'Sumatra Utara',
            'phone' => '6281264822782',
            'address' => 'Jalan Imam Bonjol, Gang Sungai, Nomor. 10, Kel. Aek Tampang, Padang Sidempuan, Sumatera Utara',
            'lat' => 1.3780,
            'lng' => 99.2715,
            'featured' => false,
        ],
        [
            'name' => 'DOBHA DISTRIBUTION STORE',
            'city' => 'Cianjur',
            'province' => 'Jawa Barat',
            'phone' => '6281998998626',
            'address' => 'Jl. Arwinda Kp sasak rt. 004/007 no.45, Jamali, Kec. Mande, Kabupaten Cianjur, Jawa Barat 43292',
            'lat' => -6.8094,
            'lng' => 107.1188,
            'featured' => false,
        ],
        [
            'name' => 'PT ASAH INTERNATIONAL TRADE',
            'city' => 'Bogor',
            'province' => 'Jawa Barat',
            'phone' => '6281380588813',
            'address' => 'Jl. Raya Kota Wisata, Limus Nunggal, Kec. Cileungsi, Kabupaten Bogor, Jawa Barat 16820, Indonesia',
            'lat' => -6.3943,
            'lng' => 106.9167,
            'featured' => false,
        ],
    ],
];